spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/city_guide
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        persistence:
          sharedCache:
            # enable selective caching mode - only entities with @Cacheable annotation will use L2 cache
            mode: ENABLE_SELECTIVE

# App properties
city-guide:
    security:
      jwt-secret: 6jiXqVnCaCTmXhZmuZ7k
      jwt-expiration-ms: 86400000
